name: Build and Push Backend Docker Image

on:
  push:
    branches:
      - ci-cd  # Trigger the workflow on push to the ci-cd branch

jobs:
  # Compile job
  compile:
    runs-on: ubuntu-latest
    name: Compile Back-end
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full history for submodules, if needed

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'  # Use Amazon Corretto JDK
          java-version: 17  # Specify Java version 17

      - name: Make mvnw executable
        run: chmod +x ./mvnw  # Ensure the mvnw script is executable

      - name: Compile using Maven
        run: ./mvnw clean compile  # Use Maven wrapper to compile

  # Build job
  build:
    runs-on: ubuntu-latest
    name: Build Back-end
    needs: [compile]  # Ensure this job only runs after compile
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full history

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Build the project
        run: ./mvnw clean package  # Use Maven wrapper to build the project

  # Docker build and push job
  build-image:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: [build]  # This job depends on the 'build' job
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full history

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Docker Hub username from secrets
          password: ${{ secrets.DOCKER_TOKEN }}  # Docker Hub token from secrets

      - name: Build and push Docker image to Docker Hub
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/parapharmacy-backend:latest .  # Build the Docker image
          docker push ${{ secrets.DOCKER_USERNAME }}/parapharmacy-backend:latest  # Push the Docker image to Docker Hub
