name: Build and Push front Docker Image

on:
  push:
    branches:
      - ci-cd


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image for frontend
        run: |
          docker build -f ./front/Dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}/parapharmacy-frontend:latest ./front
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/parapharmacy-frontend:latest
