  # Docker build and push job
  build-image:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: [build]  # This job depends on the 'build' job
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full history

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}  # Docker Hub username from secrets
          password: ${{ secrets.DOCKERHUB_TOKEN }}  # Docker Hub token from secrets

      - name: Build and push Docker image to Docker Hub
        run: |
          docker build -f ./back/Dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}/parapharmacy-backend:latest ./back  # Build Docker image from /back directory
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/parapharmacy-backend:latest  # Push Docker image to Docker Hub
